export const  LOGIN_ROUTE = '/auth'
export const  REGISTRATION_ROUTE = '/registration'
export const  MAIN_ROUTE = '/'
export const MAP_ROUTE = '/map'
export const GOOGLE_API_TOKEN_ROUTE = '/google_api_token'
export const CALENDAR_ROUTE = '/calendar'
export const ACCOUNT_ROUTE = '/account'
